"""phone number added

Revision ID: 408a9667b976
Revises: f62487905b5b
Create Date: 2026-03-18 07:41:47.808781

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '408a9667b976'
down_revision = 'f62487905b5b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('mobile', sa.String(length=20), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('mobile')

    # ### end Alembic commands ###
